# Generated by Django 3.2.7 on 2021-09-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=250, verbose_name='Название товара')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество товара')),
                ('unit', models.CharField(max_length=10, verbose_name='Единица измерения')),
                ('price', models.PositiveIntegerField(verbose_name='Цена товара')),
                ('date', models.DateField(verbose_name='Дата последней поставки или отгрузки')),
            ],
        ),
    ]
