# Generated by Django 3.2.7 on 2021-09-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='database',
            options={'verbose_name': 'База данных', 'verbose_name_plural': 'Базы данных'},
        ),
        migrations.AlterField(
            model_name='database',
            name='unit',
            field=models.CharField(choices=[('Штук', 'Штук'), ('Килограмм', 'Килограмм'), ('Литров', 'Литров')], max_length=10, verbose_name='Единица измерения'),
        ),
    ]
